    version: "3.8"
    services:
      app:
        build: .
        expose:
          ["5000"]
        networks:
          - app-network
      nginx:
        image: nginx:latest
        ports:
          - "8080:80"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - app
        networks:
          - app-network
    networks:
      app-network:
        driver: bridge